config/routes.rb
PaperClub::Application.routes.draw do
  root :to => 'welcome#index'
  match "/app" => "app#index", :via => :get

  match '/api/signin', to: 'sessions#create', via: :post
  match '/api/signout', to: 'sessions#destroy', via: :delete

  match '/signin', to: 'welcome#signin', via: :get
  match '/signup', to: 'welcome#signup', via: :get
  match '/signout', to: 'sessions#destroy'

  match '/browsers', to: 'browser#index', via: :get

  match '/invitations/:token', to: 'invitations#accept', via: :get
  match '/api/clubs/:id/invitation', to: 'api/clubs#invite', via: :post
  
  match '/api/avatar', to: 'api/users#uploadAvatar', via: :post
  
  match 'stats(/:action)' => 'statistics#index', :as => :statistics

  namespace :debug do
    match "/login" => "login#index", :via => :get

    match "/clubs" => "clubs#index", :via => :get

    match "/clubs/:club_id" => "clubs#show", :via => :get

    match "/papers/:paper_id" => "papers#show", :via => :get
  end

  namespace :api do
    resources :users, only: [:create, :update, :show] 

    resources :clubs do
      resources :users, only: [:index, :show, :destroy]

      resources :papers, only: [:index, :create]

      resources :tags, only: [:index, :create]
    end

    resources :papers, only: [:show, :update, :destroy] do
      resources :tags, only: [:index, :create, :destroy]

      resources :notes, only: [:index, :create]
    end

    resources :tags, only: [:update, :destroy]

    resources :notes, only: [:update, :destroy] do
      resources :replies, only: [:index, :create]
    end

    resources :replies, only: [:update, :destroy]
  end
  
  match "/api/fulltext/:paper_id/all.css"   => "api/fulltext#css",        :via => :get
  match "/api/fulltext/:paper_id/pages/:page_num"  => "api/fulltext#pages",      :via => :get
  match "/api/fulltext/:paper_id/download"  => "api/fulltext#download",   :via => :get
  match "/api/fulltext/:paper_id/ready"     => "api/fulltext#ready?",     :via => :get
  match "/api/fulltext/:paper_id/counter"   => "api/fulltext#counter",    :via => :post

end

app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :users, :through => :memberships
  has_many :memberships, :foreign_key => "club_id", :dependent => :destroy

  has_many :papers, :dependent => :destroy
  has_many :tags,   :dependent => :destroy
  has_many :notes

  validate :name, presence: true

  def as_json(options)
    admins = []
    {
      :id           => self.id, 
      :name         => self.name,
      :description  => self.description,
      :num_papers   => self.num_papers,
      :num_notes    => self.num_comments,
      :num_members  => self.users.count,
      :users        => self.users.map { |u|
                          if u.memberships.find_by_club_id(self.id).role == 'admin'
                            admins << u.id 
                          end
                          u.as_json(options)
                       },
      :admins       => admins
    }
  end

  default_scope :order => 'clubs.created_at DESC'

  def accep_member(user, role)
    membership = Membership.create(:club_id => club.id, 
                                   :user_id => user.id,
                                   :role => role)
  end

  def add_tag(name)
    tag = Tag.find_or_create_by_name(name, self.id)
  end

  def del_tag(name)
    tag = self.tags.find_by_name(name)
    tag.destroy
  end

  def self.join_member(club_id, user_id) 
    membership = Membership.create(:club_id => club_id, 
                                   :user_id => user_id,
                                   :role => "member")
  end

  #===============================================
  # Demo club
  #   A demo club is created with every new user
  #   to demonstrate features of PaperClub
  #
  # TODO: not hardcode demo papers' UUID but 
  # store them in database
  #===============================================

  @@demo_papers_uuid = ["fX+MBHVGPVl1SFL0odGFjQ", 
                        "0I9c9cA2fT1m6B71lxevMg", 
                        "R4faRsm5HLaffzRJ4gshDw", 
                        "NWAsJp_iYfniFGAJEwhedw", 
                        "8wULVYbd_sXaDXGTOKavqA", 
                        "kJ_7YNQt7p8AGzsM_bFzfw", 
                        "WmhmHRCENwbMtlz8+Ga6mQ"]

  @@demo_papers_correct_titles = {
    "fX+MBHVGPVl1SFL0odGFjQ" => "Reconstruction of the Genomes",
    "R4faRsm5HLaffzRJ4gshDw" => "How To Choose a Good Scientific Problem",
    "kJ_7YNQt7p8AGzsM_bFzfw" => "An Introduction To Compressive Sampling",
    "WmhmHRCENwbMtlz8+Ga6mQ" => "Spintronics: Fundamentals and applications"
  }

  @@demo_papers = {
    "fX+MBHVGPVl1SFL0odGFjQ" => {
      :title => "Reconstruction of the Genomes",
      :tags  => ["Science magazine", "biology", "genome"]
    },
    "0I9c9cA2fT1m6B71lxevMg" => {
      :tags  => []
    },
    "R4faRsm5HLaffzRJ4gshDw" => {
      :title => "How To Choose a Good Scientific Problem",
      :tags  => ["Molecular Cell"]
    },
    "NWAsJp_iYfniFGAJEwhedw" => {
      :tags  => []
    },
    "8wULVYbd_sXaDXGTOKavqA" => {
    
    },
    "kJ_7YNQt7p8AGzsM_bFzfw" => {
      :title => "An Introduction To Compressive Sampling",
      :tags  => []
    },
    "WmhmHRCENwbMtlz8+Ga6mQ" => {
      :title => "Spintronics: Fundamentals and applications",
      :tags  => []
    }
  }

  def self.demo_papers_uuid
    @@demo_papers_uuid
  end

  # This is called in db/seed.rb to prepare for demo clubs
  def self.init_for_demo_clubs
    uuids = []

    demo_papers_dir = Rails.root.join("db", "data", "demo_papers")
    Dir.glob(demo_papers_dir + "*.pdf") do |pdf_path|
      metadata = Metadata.find_or_create_from pdf_path, 
                                              :force_create => true, 
                                              :preserve_src => true

      uuid = metadata.uuid

      correct_title = @@demo_papers_correct_titles[uuid]
      metadata.update_attributes(:title => correct_title) if correct_title

      uuids << uuid
    end

    uuids
  end
end

app/controllers/api/clubs_controller.rb
class Api::ClubsController < ApplicationController

  # TODO: role!!!

  # List all clubs of current user
  #
  # URL     GET /api/clubs
  # ROLE    member
  def index
    render :json => current_user.clubs
  end

  # Show details of a club
  #
  # URL     GET /api/club/<club_id>
  # ROLE    member
  def show
    render :json => current_user.clubs.find(params[:id])
  end

  # Create a new club
  #
  # URL     POST /api/clubs
  # PARAMS  club[:name]
  #         club[:description]
  #         invititation_emails  -- array
  # ROLE    member
  def create
    club = Club.create(params[:club])
    if club
      if Membership.create(club_id: club.id, user_id: current_user.id, role: "admin")
        _send_invitations params[:invitation_emails], club.id

        render :json => club
      else
        club.destroy
        error("failed to add a new club to the user")
      end
    else
      error("failed to create a new club")
    end
  end

  # Update the details of a club
  #
  # URL     PUT /api/club/<id>
  # PARAMS  club[name]
  #         club[description]
  # ROLE    admin
  def update
    #if current_user.role == "admin"
    club = current_user.clubs.find_by_id(params[:id])
    if club
      if club.update_attributes(params[:club])
        render :json => club
      else
        error "Failed to update record"
      end
    else
      error "You don't have access to this club"
    end
  end

  # Quit or/and destroy a club
  # URL     DEL /api/club/<id>
  # ROLE    admin
  # PARAMS  delete_club
  def destroy
    club = current_user.clubs.find_by_id(params[:id])
    if club
      membership = current_user.memberships.find_by_club_id(club.id) 
      # Quit
      if membership and membership.destroy
        # Delete club (optional) if you're an admin
        club.destroy if params[:delete_club] and membership.role == "admin"

        render :json => { id: club.id } and return
      end
    end
    error "Failed to quite or delete the club"
  end

  # Send invitation to people to join this club
  # URL     POST /api/club/<id>/invitation
  # ROLE    member
  # PARAMS  emails
  def invite
    club = current_user.clubs.find_by_id(params[:id])
    if club
      _send_invitations params[:emails], club.id
      render :json => {}
      return
    end
    error "Failed to send"
  end

private
  def _send_invitations(emails, club_id)
    if emails
      emails.each { |e| 
        Invitation.create( invitor_id: current_user.id,
                           invitee_email: e,
                           club_id: club_id, 
                           role: "member")
      }
    end
  end
end

app/controllers/club_controller.rb
class ClubController < ApplicationController

  # TODO: role!!!
  # TODO: destroy

  # List all clubs of current user
  #
  # URL     GET /clubs
  # ROLE    member
  def index
    render :json => current_user.clubs
  end

  # Show details of a club
  #
  # URL     GET /club/<club_id>
  # ROLE    member
  def show
    render :json => current_user.clubs.find(params[:id])
  end

  # Create a new club
  #
  # URL     POST /clubs
  # PARAMS  club[name]
  #         club[description]
  # ROLE    member
  def create
    club = Club.create(params[:club])
    if club
      if Membership.create(club_id: club.id, user_id: current_user.id)
        render :json => club
      else
        club.destroy
        error("failed to add a new club to the user")
      end
    else
      error("failed to create a new club")
    end
  end

  # Update the details of a club
  #
  # URL     PUT /club/<club_id>
  # PARAMS  club[name]
  #         club[description]
  # ROLE    admin
  def update
    #if current_user.role == "admin"
    club = current_user.clubs.find(params[:id])
    if club
      if club.update_attributes(params[:club])
        render :json => club
      else
        error "Failed to update record"
      end
    else
      error "You don't have access to this club"
    end
  end

  # Destroy of a club
  # URL     DEL /club/<club_id>
  # ROLE    admin
  def destroy
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  # TODO: role!!!
  # TODO: destroy

  # List all clubs of current user
  #
  # URL     GET /clubs
  # ROLE    member
  def index
    render :json => current_user.clubs
  end

  # Show details of a club
  #
  # URL     GET /club/<club_id>
  # ROLE    member
  def show
    render :json => current_user.clubs.find(params[:id])
  end

  # Create a new club
  #
  # URL     POST /clubs
  # PARAMS  club[name]
  #         club[description]
  # ROLE    member
  def create
    club = Club.create(params[:club])
    if club
      if Membership.create(club_id: club.id, user_id: current_user.id)
        render :json => club
      else
        club.destroy
        error("failed to add a new club to the user")
      end
    else
      error("failed to create a new club")
    end
  end

  # Update the details of a club
  #
  # URL     PUT /club/<club_id>
  # PARAMS  club[name]
  #         club[description]
  # ROLE    admin
  def update
    #if current_user.role == "admin"
    club = current_user.clubs.find(params[:id])
    if club
      if club.update_attributes(params[:club])
        render :json => club
      else
        error "Failed to update record"
      end
    else
      error "You don't have access to this club"
    end
  end

  # Destroy of a club
  # URL     DEL /club/<club_id>
  # ROLE    admin
  def destroy
  end
end

app/controllers/debug/clubs_controller.rb
class Debug::ClubsController < ApplicationController
  def index
     
  end

  def show
    @club_id = params[:club_id]
  end
end

app/controllers/debug/login_controller.rb
class Debug::LoginController < ApplicationController
  skip_before_filter :authorize
  
  def index
     
  end
end

app/controllers/debug/papers_controller.rb
class Debug::PapersController < ApplicationController
  def show
    @paper = Paper.find(params[:paper_id])
    @paper_uuid = @paper.uuid 
  end
end

app/controllers/debug/reader_controller.rb
class Debug::ReaderController < ApplicationController
  def index
  end
end

app/helpers/debug/clubs_helper.rb
module Debug::ClubsHelper
end

app/helpers/debug/login_helper.rb
module Debug::LoginHelper
end

app/helpers/debug/papers_helper.rb
module Debug::PapersHelper
end

app/helpers/debug/reader_helper.rb
module Debug::ReaderHelper
end

app/views/debug/clubs/index.html.erb
<!-- Show all clubs of current users -->
<div>
  <h1>New club</h1>
  <%= form_for(:club, url: api_clubs_path) do |c| %>
    <div>
      <%= c.label :name %>
      <%= c.text_field :name %>
    </div>
    <div>
      <%= c.label :description %>
      <%= c.text_field :description %>
    </div>
    <div>
      <%= label_tag :invitation_emails %>
      <p>1. <%= text_field :invitation_emails, nil, :id => nil%></p>
      <p>2. <%= text_field :invitation_emails, nil, :id => nil%></p>
      <p>3. <%= text_field :invitation_emails, nil, :id => nil%></p>
    </div>
    <%= c.submit "Create", class: "" %>
  <% end %>

  <h1>Clubs of current user:</h1>
  <ul id="club-list">
  </ul>
</div>
<script type="text/template" id="club-view-template">
  <strong>Name</strong>: <p><a href="/debug/clubs/<%%= id %>"><%%= name %></a></p>
  <strong>Description</strong>: <p><%%= description %></p>
  <strong>Users</strong>: 
  <%% _.each(users, function(user) { %>
      <p><%%= user.fullname %>, <%%= user.email %></p>
  <%% }); %>
<!--  <input type="button" class="delete-club" value="Delete Club" /> -->
  <input type="button" class="quit-club" value="Quit Club" />
  <br /><br />
</script>
<script type="text/javascript">
$(function() {
  var Club = Backbone.Model.extend({
  });
  var Clubs = Backbone.Collection.extend({
    model: Club,
    url: '/api/clubs' 
  });
  var ClubView = Backbone.View.extend({
    tagName: 'li',
    initialize: function() {    
    },
    events: {
//      'click .delete-club': 'deleteClub',
      'click .quit-club': 'quitClub'
    },
    template: _.template($("#club-view-template").html()),
    render: function() {
      this.$el.empty();
      var json = this.model.toJSON();
      this.$el.append(this.template(json));
      return this;
    },
    /*deleteClub: function() {
      this.model.destroy({data: {delete_club: true}});
    },*/
    quitClub: function() {
      this.model.destroy();
    }
  });
  var ClubsView = Backbone.View.extend({
    el: "#club-list",
    initialize: function() {
      var that = this;
      this.collection.bind('add', that.addOne, that);
      this.collection.bind('reset', that.addAll, that);
      this.collection.fetch();
    },
    addOne: function(model, that, options) {
      var clubView = new ClubView({model: model});
      this.$el.append(clubView.render().$el)
    },
    addAll: function() {
      this.$el.empty();
      this.collection.each(this.addOne, this);      
    }
  });
  var clubs = new Clubs();
  var clubsView = new ClubsView({collection: clubs});
});
</script>

app/views/debug/clubs/show.html.erb
<!--- TODO: update collection automatically when a model is destroyed --->

<!-- Club info -->
<div id="club-view">
</div>
<!-- Upload -->
<div id="uploader">
  <input id="upload-btn" type="submit" value="Upload"></input>
</div>
<!-- Search -->
<div id="search">
  <div id="users"></div>
  <div id="tags"></div>
  <input type="search" placeholder='Type keywords to search papers in club' style="width: 250px;"></input>
</div>
<!-- Papers -->
<div>
  <h1>Papers:</h1>
  <ul id="paper-list">
  </ul>
</div>
<script type="text/template" id="paper-view-template">
  <p><strong>Title</strong>: 
    <a href="/debug/papers/<%%= id %>">
      <span><%%= title %></span></p>
    </a>
  <p><strong>Pub date</strong>: <span><%%= pub_date %></span></p>
  <p><strong>Tags</strong>: 
  <%% _.each(tags, function(tag, index) { %>
      <span>
        <%%= tag.name %>
      </span>
      <%% }); %>
  </p>
  <input type="button" class="deletePaper" value="Delete Paper" />
</script>
<script type="text/template" id="club-view-template">
  <h1><%%= name %></h1>
</script>
<script type="text/javascript">
var CLUB_ID = <%= @club_id %>;
$(function() {
  /*==================== Club =====================*/
  var Club = Backbone.Model.extend({
    urlRoot: "/api/clubs" 
  });
  var ClubView = Backbone.View.extend({
    el: "#club-view", 
    template: _.template($("#club-view-template").html()),
    initialize: function() {
      this.model.on('change', this.render, this);
      this.model.fetch();
    },
    render: function() 
    {
      this.$el.empty();
      var json = this.model.toJSON();
      this.$el.append(this.template(json));
      return this;
    }
  });
  var club = new Club({id: CLUB_ID});
  var clubView = new ClubView({model: club});
  /*=================== Paper =======================*/
  var Paper = Backbone.Model.extend({
    'urlRoot': '/api/papers/',
    initialize: function() {
      this.on("destory", function(model, collection, options) {
        //collection.remove(model);
      }, this);
    }
  });
  var Papers = Backbone.Collection.extend({
    model: Paper,
    url: '/api/clubs/' + CLUB_ID + '/papers',
    search: function(args) {
      // Append args to the end of url
      this.fetch({data: args})
    }
  });
  var PaperView = Backbone.View.extend({
    tagName: 'li',
    initialize: function() {    
    },
    events: {
      'click input[type=button]': 'deletePaper'
    },
    template: _.template($("#paper-view-template").html()),
    render: function() {
      this.$el.empty();
      var json = this.model.toJSON();
      this.$el.append(this.template(json));
      return this;
    },
    deletePaper: function() {
      var model = this.model,
      collection = model.collection;
      model.destroy();
      collection.remove(model);
    }
  });
  var PapersView = Backbone.View.extend({
    el: "#paper-list",
    initialize: function() {
      var that = this;
      this.collection.bind('add', that.addOne, that);
      this.collection.bind('reset', that.addAll, that);
      this.collection.fetch();
    },
    addOne: function(model, that, options) {
      var paperView = new PaperView({model: model});
      this.$el.append(paperView.render().$el)
    },
    addAll: function() {
      this.$el.empty();
      this.collection.each(this.addOne, this);      
    }
  });
  var papers = new Papers();
  var papersView = new PapersView({collection: papers});
  /*=================== Uploader =======================*/
  var UploaderView = Backbone.View.extend({
    el: "#uploader",
    initialize: function() {
      var uploader = this.uploader = new plupload.Uploader({
        runtimes : 'html5',
        browse_button : 'upload-btn',
        container: 'uploader',
        max_file_size : '10mb',
        url : '/api/clubs/' + CLUB_ID + '/papers',
        multipart_params: {
          
        },
        filters : [
            {title : "PDF files", extensions : "pdf"}
        ]
      });  
      uploader.init();
      uploader.bind('FilesAdded', function(up, files) {
        $.each(files, function(i, file) {
          uploader.start();
        });
      });
      uploader.bind('FileUploaded', function(up, file, result) {
        //var response = JSON.parse(result.response),
        //papers.create()
        papers.fetch();
      });

    }
  });
  var uploader = new UploaderView();
  /*=================== Search ================*/
  var SearchView = Backbone.View.extend({
    el: "#search",
    events: {
    },
    initialize: function() {
      this.$("input[type=search]").on('search', function(e) {
        var keywords = e.target.value;
        if(keywords)
          papers.search({ keywords: keywords })
        else
          papers.search();
      });
    }
  });  
  var searchView = new SearchView();
});
</script>